"""
LiverAI API
=============
A small FastAPI service wrapping the project's best trained model (the Soft
Voting Ensemble) so it can be deployed as a real backend instead of the
JS-approximated model embedded in liverai_predictor.html.

Endpoints:
    GET  /health          -- liveness check
    POST /predict          -- predict liver disease risk for one patient,
                               with a SHAP-based explanation

Run locally:
    pip install -r requirements.txt
    uvicorn app:app --reload --port 8000

Then open http://localhost:8000/docs for interactive API docs (Swagger UI,
auto-generated by FastAPI).
"""

import warnings
from pathlib import Path
from typing import Literal

import joblib
import numpy as np
import pandas as pd
import shap
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

warnings.filterwarnings("ignore", category=UserWarning)

BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "outputs_ensemble" / "best_model_voting_ensemble.joblib"
SCALER_PATH = BASE_DIR / "outputs_ensemble" / "scaler.joblib"
BACKGROUND_PATH = BASE_DIR / "outputs_ensemble" / "shap_background.joblib"

FEATURE_NAMES = [
    "Age", "Gender", "Total_Bilirubin", "Direct_Bilirubin",
    "Alkaline_Phosphotase", "Alamine_Aminotransferase",
    "Aspartate_Aminotransferase", "Total_Proteins", "Albumin",
    "Albumin_and_Globulin_Ratio",
]

LABELS = {
    "Age": "Age", "Gender": "Gender", "Total_Bilirubin": "Total Bilirubin",
    "Direct_Bilirubin": "Direct Bilirubin", "Alkaline_Phosphotase": "Alkaline Phosphatase",
    "Alamine_Aminotransferase": "ALT", "Aspartate_Aminotransferase": "AST",
    "Total_Proteins": "Total Proteins", "Albumin": "Albumin",
    "Albumin_and_Globulin_Ratio": "A/G Ratio",
}

app = FastAPI(
    title="LiverAI API",
    description="Predicts liver disease risk from liver-function bloodwork "
                 "using a Voting Ensemble (Logistic Regression + Random Forest + SVM). "
                 "Educational tool -- not a certified medical device.",
    version="1.0.0",
)

# Allow the static frontend (liverai_predictor.html, hosted anywhere) to call this API.
# Tighten allow_origins to your actual frontend domain(s) before going to production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

_model = None
_scaler = None
_background = None


def _load_artifacts():
    global _model, _scaler, _background
    if _model is None:
        if not MODEL_PATH.exists():
            raise RuntimeError(
                f"Model not found at {MODEL_PATH}. Run liver_disease_ensemble.py first "
                "to train and save it."
            )
        _model = joblib.load(MODEL_PATH)
        _scaler = joblib.load(SCALER_PATH)
        _background = joblib.load(BACKGROUND_PATH) if BACKGROUND_PATH.exists() else None
    return _model, _scaler, _background


@app.on_event("startup")
def startup():
    # Fail fast at boot rather than on the first request if artifacts are missing.
    _load_artifacts()


class PatientInput(BaseModel):
    age: float = Field(..., ge=0, le=120, description="Age in years")
    gender: Literal["Male", "Female", "male", "female"]
    total_bilirubin: float = Field(..., ge=0, description="mg/dL")
    direct_bilirubin: float = Field(..., ge=0, description="mg/dL")
    alkaline_phosphotase: float = Field(..., ge=0, description="IU/L")
    alamine_aminotransferase: float = Field(..., ge=0, description="ALT, IU/L")
    aspartate_aminotransferase: float = Field(..., ge=0, description="AST, IU/L")
    total_proteins: float = Field(..., ge=0, description="g/dL")
    albumin: float = Field(..., ge=0, description="g/dL")
    albumin_and_globulin_ratio: float = Field(..., ge=0, description="ratio")
    explain: bool = Field(True, description="Include a SHAP-based explanation (slightly slower)")

    class Config:
        json_schema_extra = {
            "example": {
                "age": 60, "gender": "Male", "total_bilirubin": 8.5,
                "direct_bilirubin": 4.2, "alkaline_phosphotase": 450,
                "alamine_aminotransferase": 90, "aspartate_aminotransferase": 110,
                "total_proteins": 6.0, "albumin": 2.8,
                "albumin_and_globulin_ratio": 0.6, "explain": True,
            }
        }


class Factor(BaseModel):
    feature: str
    contribution: float
    direction: Literal["toward_disease", "toward_no_disease"]


class PredictionOutput(BaseModel):
    prediction: Literal["Liver Disease", "No Disease"]
    probability: float
    risk_level: Literal["Low", "Moderate", "High"]
    top_factors: list[Factor] = []
    model: str = "Soft Voting Ensemble (Logistic Regression + Random Forest + SVM)"
    disclaimer: str = (
        "Educational tool, not a validated medical device. "
        "Consult a qualified clinician for actual medical decisions."
    )


@app.get("/health")
def health():
    try:
        _load_artifacts()
        return {"status": "ok"}
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))


@app.post("/predict", response_model=PredictionOutput)
def predict(patient: PatientInput):
    model, scaler, background = _load_artifacts()

    gender_code = 1 if patient.gender.lower() == "male" else 0
    row = {
        "Age": patient.age, "Gender": gender_code,
        "Total_Bilirubin": patient.total_bilirubin, "Direct_Bilirubin": patient.direct_bilirubin,
        "Alkaline_Phosphotase": patient.alkaline_phosphotase,
        "Alamine_Aminotransferase": patient.alamine_aminotransferase,
        "Aspartate_Aminotransferase": patient.aspartate_aminotransferase,
        "Total_Proteins": patient.total_proteins, "Albumin": patient.albumin,
        "Albumin_and_Globulin_Ratio": patient.albumin_and_globulin_ratio,
    }
    X_new = pd.DataFrame([row])[FEATURE_NAMES]
    X_scaled = pd.DataFrame(scaler.transform(X_new), columns=FEATURE_NAMES)

    proba = float(model.predict_proba(X_scaled)[0, 1])
    pred = "Liver Disease" if proba >= 0.5 else "No Disease"
    risk = "Low" if proba < 0.35 else ("Moderate" if proba < 0.65 else "High")

    top_factors: list[Factor] = []
    if patient.explain and background is not None:
        explainer = shap.KernelExplainer(model.predict_proba, background)
        sv = np.array(explainer.shap_values(X_scaled, nsamples=100, silent=True))
        contrib = sv[0, :, 1] if sv.ndim == 3 else (sv[1][0] if isinstance(sv, list) else sv[0])
        contributions = pd.Series(contrib, index=FEATURE_NAMES).sort_values(key=np.abs, ascending=False)
        top_factors = [
            Factor(
                feature=LABELS.get(feat, feat),
                contribution=round(float(val), 4),
                direction="toward_disease" if val > 0 else "toward_no_disease",
            )
            for feat, val in contributions.head(5).items()
        ]

    return PredictionOutput(
        prediction=pred, probability=round(proba, 4), risk_level=risk, top_factors=top_factors,
    )


@app.get("/")
def root():
    return {
        "name": "LiverAI API",
        "docs": "/docs",
        "health": "/health",
        "predict": "POST /predict",
    }
